package dao;

import javax.swing.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class tables {
    public static void main(String[] args) throws SQLException {
        Connection con = null;
        Statement st = null;
        try {
            con= ConnectionProvider.getCon();
            st=con.createStatement();

            if (!tableExists(st, "userdetails")) {
                st.executeUpdate(
                        "CREATE TABLE userdetails (" +
                                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                                "name VARCHAR(255) NOT NULL, " +
                                "gender VARCHAR(10) NOT NULL, " +
                                "email VARCHAR(255) UNIQUE NOT NULL, " +
                                "contact VARCHAR(20) NOT NULL, " +
                                "address VARCHAR(255) NOT NULL," +
                                "avatar_path VARCHAR(255) NOT NULL"+
                                ")"
                );
            }

            if (!tableExists(st, "userattendance")) {
                st.executeUpdate(
                        "CREATE TABLE userattendance (" +
                                "userid INT NOT NULL, " +
                                "date DATE NOT NULL, " +
                                "checkin TIMESTAMP, " +
                                "checkout TIMESTAMP, " +
                                "workduration VARCHAR(50)" +
                                ")"
                );
            }
            JOptionPane.showMessageDialog(null, "Table created/checked successfully");
        }catch (Exception ex) {
            ex.printStackTrace();
        }finally {
            try {
                if (con != null) {
                    con.close();
                }
                if (st != null) {
                    st.close();
                }
            }catch (Exception ex) {
                ex.printStackTrace();
            }
        }

    }
    private static boolean tableExists(Statement st, String tableName) throws Exception {
        ResultSet resultSet = st.executeQuery(
                "SELECT EXISTS (" +
                        "SELECT FROM information_schema.tables " +
                        "WHERE table_schema = 'public' AND table_name = '" + tableName + "'" +
                        ")"
        );
        resultSet.next();
        return resultSet.getBoolean(1);
    }

}
